

import React, { createContext, useContext, useState } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Helper to reduce repetition for keys that might not need translation in MVP or are shared
const baseTranslations = {
  app_name: 'GramSahayak',
  subtitle: 'Panchayat System',
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    ...baseTranslations,
    nav_home: 'Home',
    nav_issues: 'Issues',
    nav_schedule: 'Schedule',
    nav_drafter: 'Drafter',
    nav_schemes: 'Schemes',
    nav_connect: 'Connect',
    nav_settings: 'Settings',
    welcome: 'Welcome',
    status_msg_prefix: 'Status of Ward',
    pending: 'Pending',
    active: 'Active',
    resolved: 'Resolved',
    grievance_overview: 'Grievance Overview',
    quick_actions: 'Quick Actions',
    gram_sabha: 'Upcoming Gram Sabha',
    deadline: 'Deadline for PMAY list',
    log_title: 'Grievance Log (Jan Sunwai)',
    new_complaint: '+ New Complaint',
    villager_name: 'Villager Name',
    mobile: 'Mobile',
    category: 'Category',
    details: 'Details',
    save_btn: 'Save',
    no_complaints: 'No complaints registered yet.',
    close: 'Close',
    drafter_title: 'AI Letter Assistant',
    drafter_desc: 'Draft official letters instantly.',
    recipient: 'To Whom (Recipient)',
    subject: 'Subject',
    rough_notes: 'Details (Rough Notes)',
    tone: 'Tone',
    generate_btn: '✨ Generate Letter',
    drafting: 'Drafting...',
    copy_text: 'Copy Text',
    draft_result: 'Draft Result',
    scheme_title: 'Yojna (Schemes)',
    scheme_desc: 'Find scheme eligibility instantly.',
    search_placeholder: 'Ask about a scheme...',
    search_btn: 'SEARCH',
    suggestions: 'Suggestions',
    connect_title: 'Gram Sampark',
    connect_desc: 'Broadcast updates to WhatsApp.',
    update_topic: 'What is the update about?',
    lang_style: 'Language Style',
    create_msg_btn: '✨ Create Message',
    send_wa_btn: 'Send to Group',
    preview_msg: 'Preview Message',
    priority: 'Priority',
    p_low: 'Low',
    p_medium: 'Medium',
    p_high: 'High',
    p_urgent: 'Urgent',
    filter_status: 'Filter Status',
    filter_priority: 'Filter Priority',
    all: 'All',
    days_ago: 'days ago',
    today: 'today',
    schedule_visit: 'Schedule Visit',
    my_day: 'My Day',
    calendar: 'Calendar',
    no_events: 'No events scheduled.',
    add_event: '+ Add Event',
    event_title: 'Event Title',
    event_type: 'Type',
    event_date: 'Date',
    event_time: 'Time',
    mark_attended: 'Attend',
    postpone: 'Postpone',
    cancel: 'Cancel',
    upcoming_event: 'Upcoming Event',
    event_alert: 'You have an event in 15 mins!',
    back: 'Back',
    view_details: 'View Details',
    actions_taken: 'Actions Taken / History',
    linked_events: 'Linked Events',
    no_actions: 'No actions recorded yet.',
    no_linked_events: 'No events linked to this issue.',
    add_note: 'Add Note',
    note_placeholder: 'e.g. Spoke to Junior Engineer...',
    save_note: 'Save Note',
    link_issue_opt: 'Link Issue (Optional)',
    select_issue: 'Select Issue',
    // Registration
    setup_profile: 'Setup Profile',
    enter_details: 'Enter your details to generate personalized official letters and reports.',
    full_name: 'Your Full Name',
    ward_no: 'Ward Number',
    panchayat_name: 'Panchayat Name',
    register_btn: 'Get Started',
    // Settings & Security
    settings_title: 'Settings & Security',
    security_method: 'Security Method',
    method_pin: 'Custom PIN',
    method_bio: 'Device Lock (Fingerprint/Face)',
    app_lock: 'App Lock',
    app_lock_desc: 'Secure app with your chosen method.',
    set_pin: 'Set PIN',
    change_pin: 'Change PIN',
    enter_new_pin: 'Enter New 4-Digit PIN',
    enter_pin: 'Enter PIN to Unlock',
    wrong_pin: 'Incorrect PIN. Try again.',
    lock_enabled: 'Lock Enabled',
    lock_disabled: 'Lock Disabled',
    enable: 'Enable',
    disable: 'Disable',
    unlock_bio: 'Unlock with Device',
    bio_error: 'Authentication failed. Use fallback if available.',
    setup_bio_btn: 'Setup Device Lock',
    bio_not_supported: 'Device lock not supported on this browser.',
  },
  hi: {
    ...baseTranslations,
    nav_home: 'मुख्य पृष्ठ',
    nav_issues: 'समस्याएं',
    nav_schedule: 'दिनचर्या',
    nav_drafter: 'लेखक',
    nav_schemes: 'योजनाएं',
    nav_connect: 'संपर्क',
    nav_settings: 'सेटिंग्स',
    welcome: 'नमस्ते',
    status_msg_prefix: 'वार्ड की स्थिति:',
    pending: 'लंबित',
    active: 'सक्रिय',
    resolved: 'हल हुआ',
    grievance_overview: 'शिकायत विवरण',
    quick_actions: 'त्वरित कार्य',
    gram_sabha: 'आगामी ग्राम सभा',
    deadline: 'पीएमएवाई सूची की अंतिम तिथि',
    log_title: 'शिकायत रजिस्टर (जन सुनवाई)',
    new_complaint: '+ नई शिकायत',
    villager_name: 'ग्रामवासी का नाम',
    mobile: 'मोबाइल',
    category: 'श्रेणी',
    details: 'विवरण',
    save_btn: 'सहेजें',
    no_complaints: 'कोई शिकायत दर्ज नहीं है।',
    close: 'बंद करें',
    drafter_title: 'AI पत्र लेखक',
    drafter_desc: 'तुरंत आधिकारिक पत्र लिखें।',
    recipient: 'किसे भेजना है',
    subject: 'विषय',
    rough_notes: 'विवरण (कच्चा नोट)',
    tone: 'लहज़ा',
    generate_btn: '✨ पत्र बनाएं',
    drafting: 'लिख रहा है...',
    copy_text: 'कॉपी करें',
    draft_result: 'ड्राफ्ट परिणाम',
    scheme_title: 'सरकारी योजनाएं',
    scheme_desc: 'योजना पात्रता खोजें।',
    search_placeholder: 'योजना के बारे में पूछें...',
    search_btn: 'खोजें',
    suggestions: 'सुझाव',
    connect_title: 'ग्राम संपर्क',
    connect_desc: 'व्हाट्सएप पर अपडेट भेजें।',
    update_topic: 'अपडेट किस बारे में है?',
    lang_style: 'भाषा शैली',
    create_msg_btn: '✨ संदेश बनाएं',
    send_wa_btn: 'ग्रुप में भेजें',
    preview_msg: 'संदेश पूर्वावलोकन',
    priority: 'प्राथमिकता',
    p_low: 'कम',
    p_medium: 'मध्यम',
    p_high: 'उच्च',
    p_urgent: 'अत्यावश्यक',
    filter_status: 'स्थिति फ़िल्टर',
    filter_priority: 'प्राथमिकता फ़िल्टर',
    all: 'सभी',
    days_ago: 'दिन पहले',
    today: 'आज',
    schedule_visit: 'दौरा तय करें',
    my_day: 'मेरा दिन',
    calendar: 'कैलेंडर',
    no_events: 'कोई कार्यक्रम तय नहीं है।',
    add_event: '+ कार्यक्रम जोड़ें',
    event_title: 'कार्यक्रम का शीर्षक',
    event_type: 'प्रकार',
    event_date: 'तारीख',
    event_time: 'समय',
    mark_attended: 'उपस्थित',
    postpone: 'स्थगित',
    cancel: 'रद्द',
    upcoming_event: 'आगामी कार्यक्रम',
    event_alert: '15 मिनट में आपका कार्यक्रम है!',
    back: 'वापस',
    view_details: 'विवरण देखें',
    actions_taken: 'कार्यवाही इतिहास',
    linked_events: 'जुड़े कार्यक्रम',
    no_actions: 'अभी तक कोई कार्यवाही नहीं।',
    no_linked_events: 'इस मुद्दे से कोई कार्यक्रम नहीं जुड़ा।',
    add_note: 'नोट जोड़ें',
    note_placeholder: 'जैसे: इंजीनियर से बात की...',
    save_note: 'नोट सहेजें',
    link_issue_opt: 'मुद्दा जोड़ें (वैकल्पिक)',
    select_issue: 'मुद्दा चुनें',
    // Registration
    setup_profile: 'प्रोफ़ाइल सेटअप',
    enter_details: 'व्यक्तिगत आधिकारिक पत्र और रिपोर्ट बनाने के लिए अपना विवरण दर्ज करें।',
    full_name: 'पूरा नाम',
    ward_no: 'वार्ड संख्या',
    panchayat_name: 'पंचायत का नाम',
    register_btn: 'शुरू करें',
    // Settings
    settings_title: 'सेटिंग्स और सुरक्षा',
    security_method: 'सुरक्षा विधि',
    method_pin: 'कस्टम पिन',
    method_bio: 'डिवाइस लॉक (फिंगरप्रिंट)',
    app_lock: 'ऐप लॉक',
    app_lock_desc: 'अपनी चुनी हुई विधि से ऐप सुरक्षित करें।',
    set_pin: 'पिन सेट करें',
    change_pin: 'पिन बदलें',
    enter_new_pin: 'नया 4 अंकों का पिन दर्ज करें',
    enter_pin: 'अनलॉक करने के लिए पिन दर्ज करें',
    wrong_pin: 'गलत पिन। पुनः प्रयास करें।',
    lock_enabled: 'लॉक सक्षम',
    lock_disabled: 'लॉक अक्षम',
    enable: 'सक्षम करें',
    disable: 'अक्षम करें',
    unlock_bio: 'डिवाइस से अनलॉक करें',
    bio_error: 'प्रमाणीकरण विफल।',
    setup_bio_btn: 'डिवाइस लॉक सेट करें',
    bio_not_supported: 'इस ब्राउज़र पर डिवाइस लॉक समर्थित नहीं है।',
  },
  bn: {
    ...baseTranslations,
    nav_home: 'হোম',
    nav_issues: 'অভিযোগ',
    nav_schedule: 'সময়সূচী',
    nav_drafter: 'ড্রাফটার',
    nav_schemes: 'প্রকল্প',
    nav_connect: 'সংযোগ',
    nav_settings: 'সেটিংস',
    welcome: 'স্বাগতম',
    status_msg_prefix: 'ওয়ার্ড স্থিতি:',
    pending: 'অমীমাংসিত',
    active: 'চলমান',
    resolved: 'মীমাংসিত',
    grievance_overview: 'অভিযোগের সারসংক্ষেপ',
    quick_actions: 'দ্রুত পদক্ষেপ',
    gram_sabha: 'আসন্ন গ্রাম সভা',
    deadline: 'PMAY তালিকার শেষ তারিখ',
    log_title: 'অভিযোগ লগ (জন শুনানি)',
    new_complaint: '+ নতুন অভিযোগ',
    villager_name: 'গ্রামবাসীর নাম',
    mobile: 'মোবাইল',
    category: 'বিভাগ',
    details: 'বিবরণ',
    save_btn: 'সংরক্ষণ',
    no_complaints: 'এখনও কোন অভিযোগ নেই।',
    close: 'বন্ধ করুন',
    drafter_title: 'AI চিঠি লেখক',
    drafter_desc: 'অফিসিয়াল চিঠি লিখুন।',
    recipient: 'প্রাপক',
    subject: 'বিষয়',
    rough_notes: 'বিবরণ',
    tone: 'স্বর',
    generate_btn: '✨ চিঠি তৈরি করুন',
    drafting: 'লিখছে...',
    copy_text: 'কপি করুন',
    draft_result: 'খসড়া ফলাফল',
    scheme_title: 'সরকারি প্রকল্প',
    scheme_desc: 'প্রকল্পের যোগ্যতা খুঁজুন।',
    search_placeholder: 'প্রকল্প সম্পর্কে জিজ্ঞাসা করুন...',
    search_btn: 'অনুসন্ধান',
    suggestions: 'পরামর্শ',
    connect_title: 'গ্রাম সংযোগ',
    connect_desc: 'হোয়াটসঅ্যাপ আপডেট পাঠান।',
    update_topic: 'আপডেট কি সম্পর্কে?',
    lang_style: 'ভাষার শৈলী',
    create_msg_btn: '✨ বার্তা তৈরি করুন',
    send_wa_btn: 'গ্রুপে পাঠান',
    preview_msg: 'বার্তা প্রিভিউ',
    priority: 'অগ্রাধিকার',
    p_low: 'কম',
    p_medium: 'মাঝারি',
    p_high: 'উচ্চ',
    p_urgent: 'জরুরী',
    filter_status: 'স্ট্যাটাস ফিল্টার',
    filter_priority: 'অগ্রাধিকার ফিল্টার',
    all: 'সব',
    days_ago: 'দিন আগে',
    today: 'আজ',
    schedule_visit: 'ভিজিট শিডিউল করুন',
    my_day: 'আমার দিন',
    calendar: 'ক্যালেন্ডার',
    no_events: 'কোন ইভেন্ট নির্ধারিত নেই।',
    add_event: '+ ইভেন্ট যোগ করুন',
    event_title: 'ইভেন্টের নাম',
    event_type: 'ধরন',
    event_date: 'তারিখ',
    event_time: 'সময়',
    mark_attended: 'উপস্থিত',
    postpone: 'স্থগিত',
    cancel: 'বাতিল',
    upcoming_event: 'আসন্ন ইভেন্ট',
    event_alert: '১৫ মিনিটের মধ্যে আপনার ইভেন্ট আছে!',
    back: 'ফিরে যান',
    view_details: 'বিস্তারিত দেখুন',
    actions_taken: 'গৃহীত পদক্ষেপ',
    linked_events: 'সংযুক্ত ইভেন্ট',
    no_actions: 'এখনও কোন পদক্ষেপ নেই।',
    no_linked_events: 'কোন ইভেন্ট যুক্ত নেই।',
    add_note: 'নোট যোগ করুন',
    note_placeholder: 'যেমন: ইঞ্জিনিয়ারের সাথে কথা হয়েছে...',
    save_note: 'সংরক্ষণ',
    link_issue_opt: 'সমস্যা লিঙ্ক করুন',
    select_issue: 'সমস্যা নির্বাচন করুন',
    // Registration
    setup_profile: 'প্রোফাইল সেটআপ',
    enter_details: 'আপনার বিবরণ লিখুন।',
    full_name: 'পুরো নাম',
    ward_no: 'ওয়ার্ড নম্বর',
    panchayat_name: 'পঞ্চায়েত নাম',
    register_btn: 'শুরু করুন',
    // Settings
    settings_title: 'সেটিংস এবং নিরাপত্তা',
    security_method: 'নিরাপত্তা পদ্ধতি',
    method_pin: 'কাস্টম পিন',
    method_bio: 'ডিভাইস লক (আঙুলের ছাপ)',
    app_lock: 'অ্যাপ লক',
    app_lock_desc: 'অ্যাপ লক করুন।',
    set_pin: 'পিন সেট করুন',
    change_pin: 'পিন পরিবর্তন করুন',
    enter_new_pin: 'নতুন ৪-সংখ্যার পিন লিখুন',
    enter_pin: 'আনলক করতে পিন দিন',
    wrong_pin: 'ভুল পিন। আবার চেষ্টা করুন।',
    lock_enabled: 'লক চালু',
    lock_disabled: 'লক বন্ধ',
    enable: 'চালু করুন',
    disable: 'বন্ধ করুন',
    unlock_bio: 'ডিভাইস দিয়ে আনলক করুন',
    bio_error: 'যাচাইকরণ ব্যর্থ হয়েছে।',
    setup_bio_btn: 'ডিভাইস লক সেট করুন',
    bio_not_supported: 'এই ব্রাউজারে সমর্থিত নয়।',
  },
  te: {
    ...baseTranslations,
    nav_home: 'హోమ్',
    nav_issues: 'సమస్యలు',
    nav_schedule: 'షెడ్యూల్',
    nav_drafter: 'లేఖలు',
    nav_schemes: 'పథకాలు',
    nav_connect: 'కనెక్ట్',
    nav_settings: 'సెట్టింగ్స్',
    welcome: 'స్వాగతం',
    status_msg_prefix: 'వార్డు స్థితి:',
    pending: 'పెండింగ్',
    active: 'కొనసాగుతోంది',
    resolved: 'పరిష్కరించబడింది',
    grievance_overview: 'ఫిర్యాదుల అవలోకనం',
    quick_actions: 'త్వరిత చర్యలు',
    gram_sabha: 'రాబోయే గ్రామ సభ',
    deadline: 'PMAY గడువు',
    log_title: 'ఫిర్యాదుల చిట్టా',
    new_complaint: '+ కొత్త ఫిర్యాదు',
    villager_name: 'గ్రామస్తుని పేరు',
    mobile: 'మొబైల్',
    category: 'వర్గం',
    details: 'వివరాలు',
    save_btn: 'భద్రపరచు',
    no_complaints: 'ఫిర్యాదులు లేవు.',
    close: 'మూసివేయి',
    drafter_title: 'AI లేఖ రచయిత',
    drafter_desc: 'అధికారిక లేఖలను వ్రాయండి.',
    recipient: 'స్వీకర్త',
    subject: 'విషయం',
    rough_notes: 'వివరాలు',
    tone: 'శైలి',
    generate_btn: '✨ లేఖను సృష్టించు',
    drafting: 'వ్రాస్తోంది...',
    copy_text: 'కాపీ చేయండి',
    draft_result: 'లేఖ ఫలితం',
    scheme_title: 'ప్రభుత్వ పథకాలు',
    scheme_desc: 'అర్హత వివరాలు పొందండి.',
    search_placeholder: 'పథకం గురించి అడగండి...',
    search_btn: 'వెతకండి',
    suggestions: 'సూచనలు',
    connect_title: 'గ్రామ సంపర్క్',
    connect_desc: 'వాట్సాప్ అప్‌డేట్‌లు పంపండి.',
    update_topic: 'అప్‌డేట్ దేని గురించి?',
    lang_style: 'భాష',
    create_msg_btn: '✨ సందేశం సృష్టించు',
    send_wa_btn: 'గ్రూప్‌కి పంపండి',
    preview_msg: 'సందేశం చూడండి',
    priority: 'ప్రాధాన్యత',
    p_low: 'తక్కువ',
    p_medium: 'మధ్యస్థం',
    p_high: 'అధిక',
    p_urgent: 'అత్యవసరం',
    filter_status: 'స్థితి ఫిల్టర్',
    filter_priority: 'ప్రాధాన్యత ఫిల్టర్',
    all: 'అన్ని',
    days_ago: 'రోజుల క్రితం',
    today: 'ఈ రోజు',
    schedule_visit: 'సందర్శన షెడ్యూల్',
    my_day: 'నా రోజు',
    calendar: 'క్యాలెండర్',
    no_events: 'ఏ కార్యక్రమాలు లేవు.',
    add_event: '+ ఈవెంట్ జోడించు',
    event_title: 'కార్యక్రమం పేరు',
    event_type: 'రకం',
    event_date: 'తేదీ',
    event_time: 'సమయం',
    mark_attended: 'హాజరయ్యారు',
    postpone: 'వాయిదా',
    cancel: 'రద్దు',
    upcoming_event: 'రాబోయే కార్యక్రమం',
    event_alert: '15 నిమిషాల్లో మీకు కార్యక్రమం ఉంది!',
    back: 'వెనుకకు',
    view_details: 'వివరాలు చూడండి',
    actions_taken: 'తీసుకున్న చర్యలు',
    linked_events: 'లింక్ చేసిన ఈవెంట్స్',
    no_actions: 'ఇంకా చర్యలు తీసుకోలేదు.',
    no_linked_events: 'ఈ సమస్యకు ఈవెంట్స్ లేవు.',
    add_note: 'గమనిక జోడించు',
    note_placeholder: 'ఉదా: ఇంజనీర్‌తో మాట్లాడాను...',
    save_note: 'సేవ్ చేయండి',
    link_issue_opt: 'సమస్యను లింక్ చేయండి',
    select_issue: 'సమస్యను ఎంచుకోండి',
    // Registration
    setup_profile: 'ప్రొఫైల్ సెటప్',
    enter_details: 'మీ వివరాలను నమోదు చేయండి.',
    full_name: 'పూర్తి పేరు',
    ward_no: 'వార్డు సంఖ్య',
    panchayat_name: 'పంచాయతీ పేరు',
    register_btn: 'ప్రారంభించండి',
    // Settings
    settings_title: 'సెట్టింగులు & భద్రత',
    security_method: 'భద్రతా విధానం',
    method_pin: 'కస్టమ్ పిన్',
    method_bio: 'డివైస్ లాక్ (ఫింగర్ ప్రింట్)',
    app_lock: 'యాప్ లాక్',
    app_lock_desc: 'యాప్‌ను సురక్షితం చేయండి.',
    set_pin: 'పిన్ సెట్ చేయండి',
    change_pin: 'పిన్ మార్చండి',
    enter_new_pin: 'కొత్త 4 అంకెల పిన్ నమోదు చేయండి',
    enter_pin: 'అన్‌లాక్ చేయడానికి పిన్ నమోదు చేయండి',
    wrong_pin: 'తప్పు పిన్. మళ్ళీ ప్రయత్నించండి.',
    lock_enabled: 'లాక్ ప్రారంభించబడింది',
    lock_disabled: 'లాక్ నిలిపివేయబడింది',
    enable: 'ప్రారంభించు',
    disable: 'నిలిపివేయి',
    unlock_bio: 'పరికరాన్ని అన్‌లాక్ చేయండి',
    bio_error: 'ప్రామాణీకరణ విఫలమైంది.',
    setup_bio_btn: 'డివైస్ లాక్ సెటప్',
    bio_not_supported: 'ఈ బ్రౌజర్‌లో మద్దతు లేదు.',
  },
  ta: {
    ...baseTranslations,
    nav_home: 'முகப்பு',
    nav_issues: 'புகார்கள்',
    nav_schedule: 'அட்டவணை',
    nav_drafter: 'கடிதம்',
    nav_schemes: 'திட்டங்கள்',
    nav_connect: 'தொடர்பு',
    nav_settings: 'அமைப்புகள்',
    welcome: 'வணக்கம்',
    status_msg_prefix: 'வார்டு நிலை:',
    pending: 'நிலுவை',
    active: 'செயலில்',
    resolved: 'தீர்க்கப்பட்டது',
    grievance_overview: 'புகார் கண்ணோட்டம்',
    quick_actions: 'விரைவு செயல்கள்',
    gram_sabha: 'கிராம சபை',
    deadline: 'காலக்கெடு',
    log_title: 'புகார் பதிவு',
    new_complaint: '+ புதிய புகார்',
    villager_name: 'பெயர்',
    mobile: 'கைபேசி',
    category: 'வகை',
    details: 'விவரங்கள்',
    save_btn: 'சேமி',
    no_complaints: 'புகார்கள் இல்லை.',
    close: 'மூடு',
    drafter_title: 'AI கடித உதவியாளர்',
    drafter_desc: 'அலுவலக கடிதங்களை எழுதவும்.',
    recipient: 'பெறுநர்',
    subject: 'பொருள்',
    rough_notes: 'குறிப்புகள்',
    tone: 'தொனி',
    generate_btn: '✨ கடிதம் உருவாக்கு',
    drafting: 'எழுதுகிறது...',
    copy_text: 'நகலெடு',
    draft_result: 'கடித முடிவு',
    scheme_title: 'அரசு திட்டங்கள்',
    scheme_desc: 'திட்ட விவரங்களை தேடவும்.',
    search_placeholder: 'திட்டம் பற்றி கேளுங்கள்...',
    search_btn: 'தேடு',
    suggestions: 'பரிந்துரைகள்',
    connect_title: 'கிராம தொடர்பு',
    connect_desc: 'வாட்ஸ்அப் செய்தி அனுப்பவும்.',
    update_topic: 'தகவல் என்ன?',
    lang_style: 'மொழி',
    create_msg_btn: '✨ செய்தி உருவாக்கு',
    send_wa_btn: 'குழுவிற்கு அனுப்பு',
    preview_msg: 'முன்னோட்டம்',
    priority: 'முன்னுரிமை',
    p_low: 'குறைந்த',
    p_medium: 'நடுத்தர',
    p_high: 'உயர்',
    p_urgent: 'அவசரம்',
    filter_status: 'நிலை வடிகட்டி',
    filter_priority: 'முன்னுரிமை வடிகட்டி',
    all: 'எல்லாம்',
    days_ago: 'நாட்களுக்கு முன்',
    today: 'இன்று',
    schedule_visit: 'பார்வையிடல்',
    my_day: 'என் நாள்',
    calendar: 'நாட்காட்டி',
    no_events: 'நிகழ்வுகள் இல்லை.',
    add_event: '+ நிகழ்வு சேர்',
    event_title: 'நிகழ்வு தலைப்பு',
    event_type: 'வகை',
    event_date: 'தேதி',
    event_time: 'நேரம்',
    mark_attended: 'கலந்துகொண்டார்',
    postpone: 'ஒத்திவை',
    cancel: 'ரத்து',
    upcoming_event: 'வரவிருக்கும் நிகழ்வு',
    event_alert: '15 நிமிடங்களில் உங்களுக்கு நிகழ்வு உள்ளது!',
    back: 'திரும்ப',
    view_details: 'விவரங்களைக் காண்க',
    actions_taken: 'எடுக்கப்பட்ட நடவடிக்கைகள்',
    linked_events: 'இணைக்கப்பட்ட நிகழ்வுகள்',
    no_actions: 'நடவடிக்கைகள் இல்லை.',
    no_linked_events: 'இந்த சிக்கலுக்கு நிகழ்வுகள் இல்லை.',
    add_note: 'குறிப்பு சேர்',
    note_placeholder: 'எ.கா: பொறியாளரிடம் பேசினார்...',
    save_note: 'சேமி',
    link_issue_opt: 'சிக்கலை இணைக்கவும்',
    select_issue: 'சிக்கலைத் தேர்ந்தெடுக்கவும்',
    // Registration
    setup_profile: 'சுயவிவர அமைப்பு',
    enter_details: 'உங்கள் விவரங்களை உள்ளிடவும்.',
    full_name: 'முழு பெயர்',
    ward_no: 'வார்டு எண்',
    panchayat_name: 'பஞ்சாயத்து பெயர்',
    register_btn: 'தொடங்கவும்',
    // Settings
    settings_title: 'அமைப்புகள் & பாதுகாப்பு',
    security_method: 'பாதுகாப்பு முறை',
    method_pin: 'தனிப்பயன் பின்',
    method_bio: 'சாதன பூட்டு (கைரேகை)',
    app_lock: 'செயலி பூட்டு',
    app_lock_desc: 'செயலியை பாதுகாக்கவும்.',
    set_pin: 'PIN அமை',
    change_pin: 'PIN மாற்று',
    enter_new_pin: 'புதிய 4 இலக்க PIN',
    enter_pin: 'திறக்க PIN ஐ உள்ளிடவும்',
    wrong_pin: 'தவறான PIN. மீண்டும் முயற்சிக்கவும்.',
    lock_enabled: 'பூட்டு இயக்கப்பட்டது',
    lock_disabled: 'பூட்டு முடக்கப்பட்டது',
    enable: 'இயக்கு',
    disable: 'முடக்கு',
    unlock_bio: 'சாதனத்துடன் திறக்கவும்',
    bio_error: 'அங்கீகாரம் தோல்வியடைந்தது.',
    setup_bio_btn: 'சாதன பூட்டு அமைப்பு',
    bio_not_supported: 'இந்த உலாவியில் ஆதரிக்கப்படவில்லை.',
  },
  mr: {
    ...baseTranslations,
    nav_home: 'होम',
    nav_issues: 'तक्रारी',
    nav_schedule: 'वेळापत्रक',
    nav_drafter: 'पत्रलेखक',
    nav_schemes: 'योजना',
    nav_connect: 'संपर्क',
    nav_settings: 'सेटिंग्ज',
    welcome: 'नमस्कार',
    status_msg_prefix: 'वार्ड स्थिती:',
    pending: 'प्रलंबित',
    active: 'सक्रिय',
    resolved: 'सोडवले',
    grievance_overview: 'तक्रार आढावा',
    quick_actions: 'द्रुत क्रिया',
    gram_sabha: 'ग्रामसभा',
    deadline: 'मुदत',
    log_title: 'तक्रार नोंदवही',
    new_complaint: '+ नवीन तक्रार',
    villager_name: 'नाव',
    mobile: 'मोबाईल',
    category: 'श्रेणी',
    details: 'तपशील',
    save_btn: 'जतन करा',
    no_complaints: 'तक्रारी नाहीत.',
    close: 'बंद',
    drafter_title: 'AI पत्र लेखक',
    drafter_desc: 'अधिकृत पत्रे लिहा.',
    recipient: 'प्रति',
    subject: 'विषय',
    rough_notes: 'तपशील',
    tone: 'टोन',
    generate_btn: '✨ पत्र तयार करा',
    drafting: 'लिहित आहे...',
    copy_text: 'कॉपी करा',
    draft_result: 'मसुदा',
    scheme_title: 'सरकारी योजना',
    scheme_desc: 'योजना माहिती मिळवा.',
    search_placeholder: 'योजनेबद्दल विचारा...',
    search_btn: 'शोधा',
    suggestions: 'सूचना',
    connect_title: 'ग्राम संपर्क',
    connect_desc: 'व्हॉट्सॲप अपडेट पाठवा.',
    update_topic: 'अपडेट कशाबद्दल आहे?',
    lang_style: 'भाषा',
    create_msg_btn: '✨ संदेश तयार करा',
    send_wa_btn: 'ग्रुपला पाठवा',
    preview_msg: 'पूर्वावलोकन',
    priority: 'प्राधान्य',
    p_low: 'कमी',
    p_medium: 'मध्यम',
    p_high: 'उच्च',
    p_urgent: 'तातडीचे',
    filter_status: 'स्थिती फिल्टर',
    filter_priority: 'प्राधान्य फिल्टर',
    all: 'सर्व',
    days_ago: 'दिवसांपूर्वी',
    today: 'आज',
    schedule_visit: 'भेट नियोजित करा',
    my_day: 'माझा दिवस',
    calendar: 'दिनदर्शिका',
    no_events: 'कोणतेही कार्यक्रम नाहीत.',
    add_event: '+ कार्यक्रम जोडा',
    event_title: 'कार्यक्रमाचे नाव',
    event_type: 'प्रकार',
    event_date: 'तारीख',
    event_time: 'वेळ',
    mark_attended: 'उपस्थित',
    postpone: 'पुढे ढकलले',
    cancel: 'रद्द',
    upcoming_event: 'आगामी कार्यक्रम',
    event_alert: '15 मिनिटांत तुमचा कार्यक्रम आहे!',
    back: 'मागे',
    view_details: 'तपशील पहा',
    actions_taken: 'कारवाई इतिहास',
    linked_events: 'संलग्न कार्यक्रम',
    no_actions: 'अद्याप कोणतीही कारवाई नाही.',
    no_linked_events: 'या समस्येशी जोडलेले कार्यक्रम नाहीत.',
    add_note: 'टीप जोडा',
    note_placeholder: 'उदा: अभियंत्याशी बोललो...',
    save_note: 'जतन करा',
    link_issue_opt: 'समस्या जोडा',
    select_issue: 'समस्या निवडा',
    // Registration
    setup_profile: 'प्रोफाइल सेटअप',
    enter_details: 'आपले तपशील प्रविष्ट करा.',
    full_name: 'पूर्ण नाव',
    ward_no: 'वार्ड क्रमांक',
    panchayat_name: 'पंचायतीचे नाव',
    register_btn: 'प्रारंभ करा',
    // Settings
    settings_title: 'सेटिंग्ज आणि सुरक्षा',
    security_method: 'सुरक्षा पद्धत',
    method_pin: 'कस्टम पिन',
    method_bio: 'डिव्हाइस लॉक (फिंगरप्रिंट)',
    app_lock: 'ॲप लॉक',
    app_lock_desc: 'ॲप सुरक्षित करा.',
    set_pin: 'पिन सेट करा',
    change_pin: 'पिन बदला',
    enter_new_pin: 'नवीन 4 अंकी पिन प्रविष्ट करा',
    enter_pin: 'अनलॉक करण्यासाठी पिन टाका',
    wrong_pin: 'चुकीचा पिन. पुन्हा प्रयत्न करा.',
    lock_enabled: 'लॉक सक्षम',
    lock_disabled: 'लॉक अक्षम',
    enable: 'सक्षम करा',
    disable: 'अक्षम करा',
    unlock_bio: 'डिव्हाइससह अनलॉक करा',
    bio_error: 'प्रमाणीकरण अयशस्वी.',
    setup_bio_btn: 'डिव्हाइस लॉक सेटअप',
    bio_not_supported: 'या ब्राउझरवर समर्थित नाही.',
  },
  gu: {
    ...baseTranslations,
    nav_home: 'હોમ',
    nav_issues: 'ફરિયાદો',
    nav_schedule: 'શેડ્યૂલ',
    nav_drafter: 'પત્ર લેખક',
    nav_schemes: 'યોજનાઓ',
    nav_connect: 'સંપર્ક',
    nav_settings: 'સેટિંગ્સ',
    welcome: 'સ્વાગત છે',
    status_msg_prefix: 'વોર્ડ સ્થિતિ:',
    pending: 'બાકી',
    active: 'સક્રિય',
    resolved: 'ઉકેલાયેલ',
    grievance_overview: 'ફરિયાદ ઝાંખી',
    quick_actions: 'ઝડપી ક્રિયાઓ',
    gram_sabha: 'ગ્રામસભા',
    deadline: 'અંતિમ તારીખ',
    log_title: 'ફરિયાદ લોગ',
    new_complaint: '+ નવી ફરિયાદ',
    villager_name: 'નામ',
    mobile: 'મોબાઇલ',
    category: 'શ્રેણી',
    details: 'વિગતો',
    save_btn: 'સાચવો',
    no_complaints: 'કોઈ ફરિયાદ નથી.',
    close: 'બંધ',
    drafter_title: 'AI પત્ર સહાયક',
    drafter_desc: 'સત્તાવાર પત્રો લખો.',
    recipient: 'પ્રતિ',
    subject: 'વિષય',
    rough_notes: 'વિગતો',
    tone: 'સ્વર',
    generate_btn: '✨ પત્ર બનાવો',
    drafting: 'લખી રહ્યા છે...',
    copy_text: 'કોપી',
    draft_result: 'ડ્રાફ્ટ',
    scheme_title: 'સરકારી યોજનાઓ',
    scheme_desc: 'યોજનાની માહિતી મેળવો.',
    search_placeholder: 'યોજના વિશે પૂછો...',
    search_btn: 'શોધો',
    suggestions: 'સૂચનો',
    connect_title: 'ગ્રામ સંપર્ક',
    connect_desc: 'વોટ્સએપ અપડેટ મોકલો.',
    update_topic: 'અપડેટ શું છે?',
    lang_style: 'ભાષા',
    create_msg_btn: '✨ સંદેશ બનાવો',
    send_wa_btn: 'ગ્રુપમાં મોકલો',
    preview_msg: 'પૂર્વાવલોકન',
    priority: 'પ્રાધાન્યતા',
    p_low: 'ઓછી',
    p_medium: 'મધ્યમ',
    p_high: 'ઉચ્ચ',
    p_urgent: 'તાત્કાલિક',
    filter_status: 'સ્થિતિ ફિલ્ટર',
    filter_priority: 'પ્રાધાન્યતા ફિલ્ટર',
    all: 'બધા',
    days_ago: 'દિવસો પહેલા',
    today: 'આજે',
    schedule_visit: 'મુલાકાત શેડ્યૂલ',
    my_day: 'મારો દિવસ',
    calendar: 'કેલેન્ડર',
    no_events: 'કોઈ ઇવેન્ટ નથી.',
    add_event: '+ ઇવેન્ટ ઉમેરો',
    event_title: 'ઇવેન્ટ શીર્ષક',
    event_type: 'પ્રકાર',
    event_date: 'તારીખ',
    event_time: 'સમય',
    mark_attended: 'હાજર',
    postpone: 'મુલતવી',
    cancel: 'રદ',
    upcoming_event: 'આગામી ઇવેન્ટ',
    event_alert: '15 મિનિટમાં તમારી ઇવેન્ટ છે!',
    back: 'પાછા',
    view_details: 'વિગતો જુઓ',
    actions_taken: 'પગલાં લેવામાં આવ્યા',
    linked_events: 'લિંક કરેલ ઇવેન્ટ્સ',
    no_actions: 'હજી સુધી કોઈ પગલાં નથી.',
    no_linked_events: 'કોઈ ઇવેન્ટ લિંક નથી.',
    add_note: 'નોંધ ઉમેરો',
    note_placeholder: 'દા.ત. ઈજનેર સાથે વાત કરી...',
    save_note: 'સાચવો',
    link_issue_opt: 'સમસ્યા લિંક કરો',
    select_issue: 'સમસ્યા પસંદ કરો',
    // Registration
    setup_profile: 'પ્રોફાઇલ સેટઅપ',
    enter_details: 'તમારી વિગતો દાખલ કરો.',
    full_name: 'પૂરું નામ',
    ward_no: 'વોર્ડ નંબર',
    panchayat_name: 'પંચાયતનું નામ',
    register_btn: 'શરૂ કરો',
    // Settings
    settings_title: 'સેટિંગ્સ અને સુરક્ષા',
    security_method: 'સુરક્ષા પદ્ધતિ',
    method_pin: 'કસ્ટમ પિન',
    method_bio: 'ડિવાઇસ લોક (ફિંગરપ્રિન્ટ)',
    app_lock: 'એપ્લિકેશન લોક',
    app_lock_desc: 'એપ્લિકેશન સુરક્ષિત કરો.',
    set_pin: 'પિન સેટ કરો',
    change_pin: 'પિન બદલો',
    enter_new_pin: 'નવો 4 અંકનો પિન દાખલ કરો',
    enter_pin: 'અનલૉક કરવા માટે પિન દાખલ કરો',
    wrong_pin: 'ખોટો પિન. ફરી પ્રયાસ કરો.',
    lock_enabled: 'લોક સક્ષમ',
    lock_disabled: 'લોક અક્ષમ',
    enable: 'સક્ષમ કરો',
    disable: 'અક્ષમ કરો',
    unlock_bio: 'ડિવાઇસથી અનલૉક કરો',
    bio_error: 'પ્રમાણીકરણ નિષ્ફળ.',
    setup_bio_btn: 'ડિવાઇસ લોક સેટઅપ',
    bio_not_supported: 'આ બ્રાઉઝર પર સમર્થિત નથી.',
  },
  kn: {
    ...baseTranslations,
    nav_home: 'ಮುಖಪುಟ',
    nav_issues: 'ದೂರುಗಳು',
    nav_schedule: 'ವೇಳಾಪಟ್ಟಿ',
    nav_drafter: 'ಪತ್ರ',
    nav_schemes: 'ಯೋಜನೆಗಳು',
    nav_connect: 'ಸಂಪರ್ಕ',
    nav_settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    welcome: 'ಸ್ವಾಗತ',
    status_msg_prefix: 'ವಾರ್ಡ್ ಸ್ಥಿತಿ:',
    pending: 'ಬಾಕಿ',
    active: 'ಸಕ್ರಿಯ',
    resolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    grievance_overview: 'ದೂರುಗಳ ಅವಲೋಕನ',
    quick_actions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    gram_sabha: 'ಗ್ರಾಮ ಸಭೆ',
    deadline: 'ಗಡುವು',
    log_title: 'ದೂರು ಪಟ್ಟಿ',
    new_complaint: '+ ಹೊಸ ದೂರು',
    villager_name: 'ಹೆಸರು',
    mobile: 'ಮೊಬೈಲ್',
    category: 'ವರ್ಗ',
    details: 'ವಿವರಗಳು',
    save_btn: 'ಉಳಿಸಿ',
    no_complaints: 'ದೂರುಗಳಿಲ್ಲ.',
    close: 'ಮುಚ್ಚಿ',
    drafter_title: 'AI ಪತ್ರ ಸಹಾಯಕ',
    drafter_desc: 'ಅಧಿಕೃತ ಪತ್ರಗಳನ್ನು ಬರೆಯಿರಿ.',
    recipient: 'ಸ್ವೀಕರಿಸುವವರು',
    subject: 'ವಿಷಯ',
    rough_notes: 'ವಿವರಗಳು',
    tone: 'ಧಾಟಿ',
    generate_btn: '✨ ಪತ್ರ ರಚಿಸಿ',
    drafting: 'ಬರೆಯಲಾಗುತ್ತಿದೆ...',
    copy_text: 'ನಕಲಿಸಿ',
    draft_result: 'ಕರಡು',
    scheme_title: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    scheme_desc: 'ಯೋಜನೆ ಮಾಹಿತಿಯನ್ನು ಪಡೆಯಿರಿ.',
    search_placeholder: 'ಯೋಜನೆಯ ಬಗ್ಗೆ ಕೇಳಿ...',
    search_btn: 'ಹುಡುಕಿ',
    suggestions: 'ಸಲಹೆಗಳು',
    connect_title: 'ಗ್ರಾಮ ಸಂಪರ್ಕ',
    connect_desc: 'ವಾಟ್ಸಾಪ್ ಅಪ್‌ಡೇಟ್ ಕಳುಹಿಸಿ.',
    update_topic: 'ಅಪ್‌ಡೇಟ್ ಏನು?',
    lang_style: 'ಭಾಷೆ',
    create_msg_btn: '✨ ಸಂದೇಶ ರಚಿಸಿ',
    send_wa_btn: 'ಗುಂಪಿಗೆ ಕಳುಹಿಸಿ',
    preview_msg: 'ಮುನ್ನೋಟ',
    priority: 'ಆದ್ಯತೆ',
    p_low: 'ಕಡಿಮೆ',
    p_medium: 'ಮಧ್ಯಮ',
    p_high: 'ಹೆಚ್ಚಿನ',
    p_urgent: 'ತುರ್ತು',
    filter_status: 'ಸ್ಥಿತಿ ಫಿಲ್ಟರ್',
    filter_priority: 'ಆದ್ಯತೆ ಫಿಲ್ಟರ್',
    all: 'ಎಲ್ಲಾ',
    days_ago: 'ದಿನಗಳ ಹಿಂದೆ',
    today: 'ಇಂದು',
    schedule_visit: 'ಭೇಟಿ ನಿಗದಿಪಡಿಸಿ',
    my_day: 'ನನ್ನ ದಿನ',
    calendar: 'ಕ್ಯಾಲೆಂಡರ್',
    no_events: 'ಯಾವುದೇ ಘಟನೆಗಳಿಲ್ಲ.',
    add_event: '+ ಈವೆಂಟ್ ಸೇರಿಸಿ',
    event_title: 'ಶೀರ್ಷಿಕೆ',
    event_type: 'ಬಗೆ',
    event_date: 'ದಿನಾಂಕ',
    event_time: 'ಸಮಯ',
    mark_attended: 'ಹಾಜರಾದರು',
    postpone: 'ಮುಂದೂಡಲಾಗಿದೆ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    upcoming_event: 'ಮುಂಬರುವ ಈವೆಂಟ್',
    event_alert: '15 ನಿಮಿಷಗಳಲ್ಲಿ ನಿಮಗೆ ಈವೆಂಟ್ ಇದೆ!',
    back: 'ಹಿಂದೆ',
    view_details: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    actions_taken: 'ತೆಗೆದುಕೊಂಡ ಕ್ರಮಗಳು',
    linked_events: 'ಲಿಂಕ್ ಮಾಡಿದ ಈವೆಂಟ್‌ಗಳು',
    no_actions: 'ಇನ್ನೂ ಯಾವುದೇ ಕ್ರಮಗಳಿಲ್ಲ.',
    no_linked_events: 'ಯಾವುದೇ ಈವೆಂಟ್‌ಗಳಿಲ್ಲ.',
    add_note: 'ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ',
    note_placeholder: 'ಉದಾ: ಇಂಜಿನಿಯರ್ ಜೊತೆ ಮಾತನಾಡಿದೆ...',
    save_note: 'ಉಳಿಸಿ',
    link_issue_opt: 'ಸಮಸ್ಯೆಯನ್ನು ಲಿಂಕ್ ಮಾಡಿ',
    select_issue: 'ಸಮಸ್ಯೆಯನ್ನು ಆರಿಸಿ',
    // Registration
    setup_profile: 'ಪ್ರೊಫೈಲ್ ಸೆಟಪ್',
    enter_details: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    ward_no: 'ವಾರ್ಡ್ ಸಂಖ್ಯೆ',
    panchayat_name: 'ಪಂಚಾಯತ್ ಹೆಸರು',
    register_btn: 'ಪ್ರಾರಂಭಿಸಿ',
    // Settings
    settings_title: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಭದ್ರತೆ',
    security_method: 'ಭದ್ರತಾ ವಿಧಾನ',
    method_pin: 'ಕಸ್ಟಮ್ ಪಿನ್',
    method_bio: 'ಸಾಧನ ಲಾಕ್ (ಫಿಂಗರ್‌ಪ್ರಿಂಟ್)',
    app_lock: 'ಆಪ್ ಲಾಕ್',
    app_lock_desc: 'ಆಪ್ ಅನ್ನು ಸುರಕ್ಷಿತಗೊಳಿಸಿ.',
    set_pin: 'ಪಿನ್ ಹೊಂದಿಸಿ',
    change_pin: 'ಪಿನ್ ಬದಲಾಯಿಸಿ',
    enter_new_pin: 'ಹೊಸ 4 ಅಂಕಿಯ ಪಿನ್ ನಮೂದಿಸಿ',
    enter_pin: 'ಅನ್ಲಾಕ್ ಮಾಡಲು ಪಿನ್ ನಮೂದಿಸಿ',
    wrong_pin: 'ತಪ್ಪು ಪಿನ್. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    lock_enabled: 'ಲಾಕ್ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
    lock_disabled: 'ಲಾಕ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
    enable: 'ಸಕ್ರಿಯಗೊಳಿಸಿ',
    disable: 'ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
    unlock_bio: 'ಸಾಧನದೊಂದಿಗೆ ಅನ್ಲಾಕ್ ಮಾಡಿ',
    bio_error: 'ದೃಢೀಕರಣ ವಿಫಲವಾಗಿದೆ.',
    setup_bio_btn: 'ಸಾಧನ ಲಾಕ್ ಸೆಟಪ್',
    bio_not_supported: 'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ.',
  },
  ml: {
    ...baseTranslations,
    nav_home: 'ഹോം',
    nav_issues: 'പരാതികൾ',
    nav_schedule: 'ഷെഡ്യൂൾ',
    nav_drafter: 'കത്ത്',
    nav_schemes: 'പദ്ധതികൾ',
    nav_connect: 'ബന്ധപ്പെടുക',
    nav_settings: 'ക്രമീകരണങ്ങൾ',
    welcome: 'സ്വാഗതം',
    status_msg_prefix: 'വാർഡ് നില:',
    pending: 'തീർപ്പാകാത്തവ',
    active: 'സജീവം',
    resolved: 'പരിഹരിച്ചു',
    grievance_overview: 'അവലോകനം',
    quick_actions: 'പെട്ടെന്നുള്ള കാര്യങ്ങൾ',
    gram_sabha: 'ഗ്രാമസഭ',
    deadline: 'അവസാന തീയതി',
    log_title: 'പരാതി രജിസ്റ്റർ',
    new_complaint: '+ പുതിയ പരാതി',
    villager_name: 'പേര്',
    mobile: 'മൊബൈൽ',
    category: 'വിഭാഗം',
    details: 'വിശദാംശങ്ങൾ',
    save_btn: 'സേവ് ചെയ്യുക',
    no_complaints: 'പരാതികളില്ല.',
    close: 'അടയ്ക്കുക',
    drafter_title: 'AI കത്ത് സഹായി',
    drafter_desc: 'ഔദ്യോഗിക കത്തുകൾ തയ്യാറാക്കുക.',
    recipient: 'സ്വീകർത്താവ്',
    subject: 'വിഷയം',
    rough_notes: 'വിശദാംശങ്ങൾ',
    tone: 'ശൈലി',
    generate_btn: '✨ കത്ത് തയ്യാറാക്കുക',
    drafting: 'എഴുതുന്നു...',
    copy_text: 'കോപ്പി',
    draft_result: 'ഡ്രാഫ്റ്റ്',
    scheme_title: 'സർക്കാർ പദ്ധതികൾ',
    scheme_desc: 'പദ്ധതി വിവരങ്ങൾ നേടുക.',
    search_placeholder: 'പദ്ധതിയെക്കുറിച്ച് ചോദിക്കുക...',
    search_btn: 'തിരയുക',
    suggestions: 'നിർദ്ദേശങ്ങൾ',
    connect_title: 'ഗ്രാമ സമ്പർക്കം',
    connect_desc: 'വാട്ട്‌സ്ആപ്പ് അപ്‌ഡേറ്റ് അയയ്ക്കുക.',
    update_topic: 'അപ്‌ഡേറ്റ് എന്താണ്?',
    lang_style: 'ഭാഷ',
    create_msg_btn: '✨ സന്ദേശം തയ്യാറാക്കുക',
    send_wa_btn: 'ഗ്രൂപ്പിലേക്ക് അയയ്ക്കുക',
    preview_msg: 'പ്രിവ്യൂ',
    priority: 'മുൻഗണന',
    p_low: 'കുറഞ്ഞ',
    p_medium: 'ഇടത്തരം',
    p_high: 'ഉയർന്ന',
    p_urgent: 'അടിയന്തിര',
    filter_status: 'അവസ്ഥ',
    filter_priority: 'മുൻഗണന',
    all: 'എല്ലാം',
    days_ago: 'ദിവസം മുമ്പ്',
    today: 'ഇന്ന്',
    schedule_visit: 'സന്ദർശനം',
    my_day: 'എന്റെ ദിവസം',
    calendar: 'കലണ്ടർ',
    no_events: 'ഇവന്റുകളില്ല.',
    add_event: '+ ഇവന്റ് ചേർക്കുക',
    event_title: 'ഇവന്റ്',
    event_type: 'തരം',
    event_date: 'തീയതി',
    event_time: 'സമയം',
    mark_attended: 'പങ്കെടുത്തു',
    postpone: 'മാറ്റിവച്ചു',
    cancel: 'റദ്ദാക്കുക',
    upcoming_event: 'വരാനിരിക്കുന്ന ഇവന്റ്',
    event_alert: '15 മിനിറ്റിനുള്ളിൽ നിങ്ങൾക്ക് ഒരു ഇവന്റ് ഉണ്ട്!',
    back: 'തിരികെ',
    view_details: 'വിശദാംശങ്ങൾ കാണുക',
    actions_taken: 'നടപടികൾ',
    linked_events: 'ലിങ്ക് ചെയ്ത ഇവന്റുകൾ',
    no_actions: 'ഇതുവരെ നടപടികളില്ല.',
    no_linked_events: 'ഇവന്റുകളില്ല.',
    add_note: 'കുറിപ്പ് ചേർക്കുക',
    note_placeholder: 'ഉദാ: എഞ്ചിനീയറുമായി സംസാരിച്ചു...',
    save_note: 'സേവ് ചെയ്യുക',
    link_issue_opt: 'പ്രശ്നം ലിങ്ക് ചെയ്യുക',
    select_issue: 'പ്രശ്നം തിരഞ്ഞെടുക്കുക',
    // Registration
    setup_profile: 'പ്രൊഫൈൽ സജ്ജീകരണം',
    enter_details: 'നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക.',
    full_name: 'മുഴുവൻ പേര്',
    ward_no: 'വാർഡ് നമ്പർ',
    panchayat_name: 'പഞ്ചായത്ത് പേര്',
    register_btn: 'ആരംഭിക്കുക',
    // Settings
    settings_title: 'ക്രമീകരണങ്ങളും സുരക്ഷയും',
    security_method: 'സുരക്ഷാ രീതി',
    method_pin: 'കസ്റ്റം പിൻ',
    method_bio: 'ഉപകരണ ലോക്ക് (വിരലടയാളം)',
    app_lock: 'ആപ്പ് ലോക്ക്',
    app_lock_desc: 'ആപ്പ് സുരക്ഷിതമാക്കുക.',
    set_pin: 'PIN സജ്ജമാക്കുക',
    change_pin: 'PIN മാറ്റുക',
    enter_new_pin: 'പുതിയ 4 അക്ക PIN നൽകുക',
    enter_pin: 'അൺലോക്ക് ചെയ്യാൻ PIN നൽകുക',
    wrong_pin: 'തെറ്റായ PIN. വീണ്ടും ശ്രമിക്കുക.',
    lock_enabled: 'ലോക്ക് പ്രവർത്തനക്ഷമമാണ്',
    lock_disabled: 'ലോക്ക് പ്രവർത്തനരഹിതമാണ്',
    enable: 'പ്രവർത്തനക്ഷമമാക്കുക',
    disable: 'പ്രവർത്തനരഹിതമാക്കുക',
    unlock_bio: 'ഉപകരണം ഉപയോഗിച്ച് അൺലോക്ക് ചെയ്യുക',
    bio_error: 'പ്രാമാണീകരണം പരാജയപ്പെട്ടു.',
    setup_bio_btn: 'ഉപകരണ ലോക്ക് സജ്ജീകരണം',
    bio_not_supported: 'ഈ ബ്രൗസറിൽ പിന്തുണയ്ക്കുന്നില്ല.',
  },
  pa: {
    ...baseTranslations,
    nav_home: 'ਹੋਮ',
    nav_issues: 'ਸ਼ਿਕਾਇਤਾਂ',
    nav_schedule: 'ਸਮਾਂ ਸੂਚੀ',
    nav_drafter: 'ਪੱਤਰ',
    nav_schemes: 'ਸਕੀਮਾਂ',
    nav_connect: 'ਸੰਪਰਕ',
    nav_settings: 'ਸੈਟਿੰਗਾਂ',
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    status_msg_prefix: 'ਵਾਰਡ ਸਥਿਤੀ:',
    pending: 'ਬਾਕੀ',
    active: 'ਚਲ ਰਿਹਾ ਹੈ',
    resolved: 'ਹੱਲ ਹੋ ਗਿਆ',
    grievance_overview: 'ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    quick_actions: 'ਤੁਰੰਤ ਕਾਰਵਾਈ',
    gram_sabha: 'ਗ੍ਰਾਮ ਸਭਾ',
    deadline: 'ਆਖਰੀ ਮਿਤੀ',
    log_title: 'ਸ਼ਿਕਾਇਤ ਰਜਿਸਟਰ',
    new_complaint: '+ ਨਵੀਂ ਸ਼ਿਕਾਇਤ',
    villager_name: 'ਨਾਮ',
    mobile: 'ਮੋਬਾਈਲ',
    category: 'ਸ਼੍ਰੇਣੀ',
    details: 'ਵੇਰਵੇ',
    save_btn: 'ਸੇਵ ਕਰੋ',
    no_complaints: 'ਕੋਈ ਸ਼ਿਕਾਇਤ ਨਹੀਂ।',
    close: 'ਬੰਦ ਕਰੋ',
    drafter_title: 'AI ਪੱਤਰ ਲੇਖਕ',
    drafter_desc: 'ਸਰਕਾਰੀ ਪੱਤਰ ਲਿਖੋ।',
    recipient: 'ਪ੍ਰਾਪਤਕਰਤਾ',
    subject: 'ਵਿਸ਼ਾ',
    rough_notes: 'ਵੇਰਵੇ',
    tone: 'ਲਹਿਜ਼ਾ',
    generate_btn: '✨ ਪੱਤਰ ਬਣਾਓ',
    drafting: 'ਲਿਖ ਰਿਹਾ ਹੈ...',
    copy_text: 'ਕਾਪੀ ਕਰੋ',
    draft_result: 'ਡਰਾਫਟ',
    scheme_title: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    scheme_desc: 'ਸਕੀਮ ਦੀ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰੋ।',
    search_placeholder: 'ਸਕੀਮ ਬਾਰੇ ਪੁੱਛੋ...',
    search_btn: 'ਖੋਜ',
    suggestions: 'ਸੁਝਾਅ',
    connect_title: 'ਗ੍ਰਾਮ ਸੰਪਰਕ',
    connect_desc: 'ਵਟਸਐਪ ਅਪਡੇਟ ਭੇਜੋ।',
    update_topic: 'ਅਪਡੇਟ ਕਿਸ ਬਾਰੇ ਹੈ?',
    lang_style: 'ਭਾਸ਼ਾ',
    create_msg_btn: '✨ ਸੁਨੇਹਾ ਬਣਾਓ',
    send_wa_btn: 'ਗਰੁੱਪ ਵਿੱਚ ਭੇਜੋ',
    preview_msg: 'ਝਲਕ',
    priority: 'ਤਰਜੀਹ',
    p_low: 'ਘੱਟ',
    p_medium: 'ਦਰਮਿਆਨਾ',
    p_high: 'ਉੱਚ',
    p_urgent: 'ਜ਼ਰੂਰੀ',
    filter_status: 'ਸਥਿਤੀ ਫਿਲਟਰ',
    filter_priority: 'ਤਰਜੀਹ ਫਿਲਟਰ',
    all: 'ਸਭ',
    days_ago: 'ਦਿਨ ਪਹਿਲਾਂ',
    today: 'ਅੱਜ',
    schedule_visit: 'ਮੁਲਾਕਾਤ ਤੈਅ ਕਰੋ',
    my_day: 'ਮੇਰਾ ਦਿਨ',
    calendar: 'ਕੈਲੰਡਰ',
    no_events: 'ਕੋਈ ਸਮਾਗਮ ਨਹੀਂ।',
    add_event: '+ ਸਮਾਗਮ ਸ਼ਾਮਲ ਕਰੋ',
    event_title: 'ਸਮਾਗਮ',
    event_type: 'ਕਿਸਮ',
    event_date: 'ਮਿਤੀ',
    event_time: 'ਸਮਾਂ',
    mark_attended: 'ਸ਼ਾਮਲ ਹੋਏ',
    postpone: 'ਮੁਲਤਵੀ',
    cancel: 'ਰੱਦ ਕਰੋ',
    upcoming_event: 'ਆਗਾਮી ਸਮਾਗਮ',
    event_alert: '15 ਮਿੰਟਾਂ ਵਿੱਚ ਤੁਹਾਡਾ ਸਮਾਗਮ ਹੈ!',
    back: 'ਵਾਪਸ',
    view_details: 'ਵੇਰਵੇ ਵੇਖੋ',
    actions_taken: 'ਕਾਰਵਾਈ ਇਤਿਹਾਸ',
    linked_events: 'ਲਿੰਕਡ ਸਮਾਗਮ',
    no_actions: 'ਅਜੇ ਤੱਕ ਕੋਈ ਕਾਰਵਾਈ ਨਹੀਂ।',
    no_linked_events: 'ਕੋਈ ਸਮਾਗਮ ਨਹੀਂ ਜੁੜਿਆ।',
    add_note: 'ਨੋਟ ਸ਼ਾਮਲ ਕਰੋ',
    note_placeholder: 'ਉਦਾਹਰਨ: ਇੰਜੀਨੀਅਰ ਨਾਲ ਗੱਲ ਕੀਤੀ...',
    save_note: 'ਸੇਵ ਕਰੋ',
    link_issue_opt: 'ਮੁੱਦਾ ਲਿੰਕ ਕਰੋ',
    select_issue: 'ਮੁੱਦਾ ਚੁਣੋ',
    // Registration
    setup_profile: 'ਪ੍ਰੋਫਾਈਲ ਸੈੱਟਅੱਪ',
    enter_details: 'ਆਪਣੇ ਵੇਰਵੇ ਦਰਜ ਕਰੋ।',
    full_name: 'ਪੂਰਾ ਨਾਮ',
    ward_no: 'ਵਾਰਡ ਨੰਬਰ',
    panchayat_name: 'ਪੰਚਾਇਤ ਦਾ ਨਾਮ',
    register_btn: 'ਸ਼ੁਰੂ ਕਰੋ',
    // Settings
    settings_title: 'ਸੈਟਿੰਗਾਂ ਅਤੇ ਸੁਰੱਖਿਆ',
    security_method: 'ਸੁਰੱਖਿਆ ਵਿਧੀ',
    method_pin: 'ਕਸਟਮ ਪਿੰਨ',
    method_bio: 'ਡਿਵਾਈਸ ਲਾਕ (ਫਿੰਗਰਪ੍ਰਿੰਟ)',
    app_lock: 'ਐਪ ਲਾਕ',
    app_lock_desc: 'ਐਪ ਸੁਰੱਖਿਅਤ ਕਰੋ।',
    set_pin: 'ਪਿੰਨ ਸੈੱਟ ਕਰੋ',
    change_pin: 'ਪਿੰਨ ਬਦਲੋ',
    enter_new_pin: 'ਨਵਾਂ 4 ਅੰਕਾਂ ਦਾ ਪਿੰਨ ਦਰਜ ਕਰੋ',
    enter_pin: 'ਅਨਲੌਕ ਕਰਨ ਲਈ ਪਿੰਨ ਦਰਜ ਕਰੋ',
    wrong_pin: 'ਗਲਤ ਪਿੰਨ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    lock_enabled: 'ਲਾਕ ਸਮਰਥਿਤ',
    lock_disabled: 'ਲਾਕ ਅਸਮਰਥਿਤ',
    enable: 'ਸਮਰੱਥ ਕਰੋ',
    disable: 'ਅਯੋਗ ਕਰੋ',
    unlock_bio: 'ਡਿਵਾਈਸ ਨਾਲ ਅਨਲੌਕ ਕਰੋ',
    bio_error: 'ਪ੍ਰਮਾਣਿਕਤਾ ਅਸਫਲ ਹੋਈ।',
    setup_bio_btn: 'ਡਿਵਾਈਸ ਲਾਕ ਸੈਟਅਪ',
    bio_not_supported: 'ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਤੇ ਸਮਰਥਿਤ ਨਹੀਂ।',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
